# Generated by Django 5.1.4 on 2025-02-27 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='이벤트명', max_length=125)),
                ('description', models.TextField(blank=True, help_text='설명', null=True)),
                ('seat_capacity', models.PositiveIntegerField(default=0, help_text='총 좌석수')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
